services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "${BACKEND_PORT}:5000"
        environment:
            ConnectionStrings__Default: "Server=db;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};"
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "${FRONTEND_PORT}:3000"
        depends_on:
            - backend

    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "${SA_PASSWORD}"
            ACCEPT_EULA: "${ACCEPT_EULA}"
        ports:
            - "${DB_PORT}:1433"
        volumes:
            - mssql_data:/var/opt/mssql

volumes:
    mssql_data:
