version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: realyushi/todo-list:backend-latest

        environment:
            ASPNETCORE_ENVIRONMENT: Development
            DB_CONNECTION_STRING: "Server=db;Database=${DB_NAME:-TodoList};User Id=${DB_USER:-sa};Password=${SA_PASSWORD:-YourStrongPassword!};Encrypt=true;TrustServerCertificate=true;"
            ASPNETCORE_URLS: "https://*:${BACKEND_PORT:-5001}"
            JWT_KEY: "${JWT_KEY:-thisisaverylongsecretkeypleasechangethis}"
            JWT_ISSUER: "${JWT_ISSUER:-YourIssuer}"
            JWT_AUDIENCE: "${JWT_AUDIENCE:-YourAudience}"
        ports:
            - "${BACKEND_PORT:-5001}:5001"

        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: realyushi/todo-list:frontend-latest
        ports:
            - "${FRONTEND_PORT:-443}:443"
        depends_on:
            - backend
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./frontend/Caddyfile:/etc/caddy/Caddyfile
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "${SA_PASSWORD:-YourStrongPassword!}"
            ACCEPT_EULA: "Y"
        ports:
            - "${DB_PORT:-1433}:1433"
        volumes:
            - mssql_data:/var/opt/mssql

volumes:
    mssql_data:
    caddy_data:
    caddy_config:
