services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: realyushi/todo-list:backend-latest
        ports:
            - "${BACKEND_PORT}:5001"
        environment:
            DB_CONNECTION_STRING: "Server=db;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=true; TrustServerCertificate=true;"
            ASPNETCORE_URLS: "https://*:5001"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/localhost.pfx"
            ASPNETCORE_Kestrel__Certificates__Default__Password: ""
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: realyushi/todo-list:frontend-latest
        ports:
            - "${FRONTEND_PORT}:80"
        depends_on:
            - backend
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "${SA_PASSWORD}"
            ACCEPT_EULA: "${ACCEPT_EULA}"
        ports:
            - "${DB_PORT}:1433"
        volumes:
            - mssql_data:/var/opt/mssql

volumes:
    mssql_data:
