services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "${BACKEND_PORT}:8080"
        environment:
            ConnectionStrings__Default: "Server=db;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};"
        depends_on:
            - db
        image: realyushi/todo-list:backend-latest

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "${FRONTEND_PORT}:80"
        depends_on:
            - backend
        image: realyushi/todo-list:frontend-latest

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "${SA_PASSWORD}"
            ACCEPT_EULA: "${ACCEPT_EULA}"
        ports:
            - "${DB_PORT}:1433"
        volumes:
            - mssql_data:/var/opt/mssql

volumes:
    mssql_data:
