name: Backend CI/CD

on:
    push:
        branches:
            - main
            - development
            - hotfix/**
            - feature/**
    pull_request:
        branches:
            - main
            - development

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4.0.0
              with:
                  dotnet-version: "8.0.x"

            - name: Cache NuGet packages
              uses: actions/cache@v3
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Restore dependencies
              run: dotnet restore

            - name: Create .env file
              run: |
                  echo BACKEND_PORT=${{ secrets.BACKEND_PORT }} >> src/.env
                  echo FRONTEND_PORT=${{ secrets.FRONTEND_PORT }} >> src/.env
                  echo DB_PORT=${{ secrets.DB_PORT }} >> src/.env
                  echo DB_NAME=${{ secrets.DB_NAME }} >> src/.env
                  echo DB_USER=${{ secrets.DB_USER }} >> src/.env
                  echo SA_PASSWORD=${{ secrets.SA_PASSWORD }} >> src/.env
                  echo ACCEPT_EULA=${{ secrets.ACCEPT_EULA }} >> src/.env

            - name: Build
              run: dotnet build --no-restore -c Release
            - name: Run tests
              run: dotnet test --no-build --configuration Release --verbosity normal
