name: Build and deploy ASP.Net Core app to Azure Web App - todo-be

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"

            - name: Build with dotnet
              run: dotnet build ./backend --configuration Release

            - name: dotnet publish
              run: dotnet publish ./backend -c Release -o ${{env.DOTNET_ROOT}}/myapp

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: .net-app
                  path: ${{env.DOTNET_ROOT}}/myapp

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: .net-app

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB5C82AC9CC94ED6BC81445843B910D4 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56FF6C6C705E44DA92F88803B8CD4768 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBC13AF357B24458B53FDA23B797D401 }}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: "todo-be"
                  slot-name: "Production"
                  package: .
