name: Docker CI/CD

on:
    push:
        branches:
            - main

jobs:
    docker-build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push Docker images using Docker Compose
              run: |
                  docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
                  docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
