name: Frontend CI/CD

on:
    push:
        branches:
            - main
            - development
            - hotfix/**
            - feature/**
    pull_request:
        branches:
            - main
            - development

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20.9.0
            - run: npm ci
            # - run: npm run lint
            # - run: npm run test-cucumber > test-output.txt || true # Prevent fail and continue
            # - run: npm run test-jest
            - run: npm run build

            # - name: Check test results
            #   run: |
            #       if grep -q "pending" test-output.txt; then
            #         echo "There are pending tests, but we'll not fail the build."
            #         echo "##[warning]There are pending implementations."
            #       fi
